### ISSUE TITLE
"Proxmark3 firmware update required" message on RDV4 even after flashing official firmware

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [AndProx/AndProx#38]
I just got my Proxmark3 RDV4. I'm on a Mac. I immediately installed the iceman fork client with Homebrew following the instructions [here](https://github.com/iceman1001/proxmark3#homebrew-mac-os-x). After that, I followed the instructions directly below it, [here](https://github.com/iceman1001/proxmark3#upgrading-homebrew-tap-formula), to flash the iceman bootrom and then fullimage. It was a while later that I discovered the ability to use AndProx on my Pixel 2 XL. I am on a custom rom, [LiquidRemix](https://forum.xda-developers.com/pixel-2-xl/development/unofficial-liquid-remix-t3843920), on Android Pie, with root with Magisk, using the rom's custom kernel, [Kirisakura Kernel](https://forum.xda-developers.com/pixel-2-xl/development/17-11-2017-kiriskura-kernel-1-0-0-t3706286), that was built inline. I have looked, and it does not have the `cdc_acm` kernel module.

Anyway, so I opted into the beta and installed AndProx on my phone. Then I hooked up my Proxmark3 RDV4 with the factory usb cable and a USB OTG adapter to my phone, opened AndProx, granted it the Storage permission, and then got this message:

![screenshot_andprox_20190204-204931](https://user-images.githubusercontent.com/9469151/52252837-d6429e00-28c1-11e9-9286-bd75a2e3bdaf.png)

Upon seeing that, I uninstalled the Iceman fork from Homebrew entirely with the intent to flash to the official bootrom and firmware. After that complete uninstall, I followed [these official Homebrew instructions](https://github.com/Proxmark/homebrew-proxmark3#homebrew-tap-of-proxmark3) to install the official client. Then I flashed the HEAD build bootrom and fullimage.

But even after following all those instructions, I still get the warning message that I'm not using the official firmware.

Here is my Proxmark3 info from my computer:

```
proxmark3> hw version

Prox/RFID mark3 RFID instrument
bootrom: master/-suspect 2019-02-05 03:16:40
os: master/-suspect 2019-02-05 03:16:42
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2018/11/28 at 08:33:11
SmartCard Slot: available

uC: AT91SAM7S512 Rev B
Embedded Processor: ARM7TDMI
Nonvolatile Program Memory Size: 512K bytes. Used: 206049 bytes (39). Free: 318239 bytes (61).
Second Nonvolatile Program Memory Size: None
Internal SRAM Size: 64K bytes
Architecture Identifier: AT91SAM7Sxx Series
Nonvolatile Program Memory Type: Embedded Flash Memory
```

```
proxmark3> hw status

#db# Memory
#db#   BIGBUF_SIZE.............40000
#db#   Available memory........40000
#db# Tracing
#db#   tracing ................1
#db#   traceLen ...............0
#db# Currently loaded FPGA image:
#db#   fpga_hf.bit built for 2s30vq100 on 2018/11/28 at 08:33:11
#db# Smart card module (ISO 7816)
#db#   version.................v3.0a
#db# LF Sampling config:
#db#   [q] divisor:           95
#db#   [b] bps:               8
#db#   [d] decimation:        1
#db#   [a] averaging:         1
#db#   [t] trigger threshold: 0
#db# USB Speed:
#db#   Sending USB packets to client...
#db#   Time elapsed:      1500ms
#db#   Bytes transferred: 864256
#db#   USB Transfer Speed PM3 -> Client = 576170 Bytes/s
#db# Various
#db#   MF_DBGLEVEL........2
#db#   ToSendMax..........-1244678412
#db#   ToSendBit..........0
```

And here's the AndProx System Info:

```
AndProx version: 2.0.4 (95)
PM3 Client version: v3.1.0/HEAD
Build timestamp: 2018-11-25T05:05:27Z
Model: Pixel 2 XL (taimen)
Product: taimen
Manufacturer: Google (Google)
RAM: 3.6 GiB (798.1 MiB free)
Android OS: 9 (API 28)
Android Build: PQ1A.190105.004

USB Host: yes
Found 1 USB device(s):
- /dev/bus/usb/001/002 (9ac4:4b8f)
  Name: proxmark3
  Could not retrieve serial number!

Found 1 suitable driver(s):
- /dev/bus/usb/001/002 (9ac4:4b8f)
  Port 0: CdcAcmSerialPort
  Detected PM3!
```

Can you please help me figure out what I've done wrong here and how to resolve it? I'd really like to be able to use AndProx.

**Comment by micolous** [comment]
Thanks for the detailed report!  It looks like your firmware build is missing version information:

```
bootrom: master/-suspect 2019-02-05 03:16:40
os: master/-suspect 2019-02-05 03:16:42
```

The fact that it says `master/-suspect` means that `mkversion.pl` (part of the Proxmark3 build script) couldn't figure out what git revision of the code you're on, which is https://github.com/Proxmark/proxmark3/issues/12

This is also present on a number of devices shipped from (primarily) Chinese sellers who do not release source code to their modifications, and [like the rest of the PM3 community](http://www.proxmark.org/forum/viewtopic.php?id=5515), _I intentionally do not wish to support these at all_.

I opened https://github.com/Proxmark/homebrew-proxmark3/issues/18 against the Homebrew repository accordingly -- because this is an issue that would impact non-AndProx users wanting to get support from Proxmark3 forums.

Part of this is fixed in the `git master` version of AndProx (not in Play Store) -- such that you'll be able to flash the firmware image [I posted in GitHub releases](https://github.com/AndProx/AndProx/releases) and still run it with iceman's (or RDV4.0) bootloader, or any other bootloader which has `git` version data.

I haven't yet got around to cutting a release with that fix, as I had been working on some other projects that were time/location sensitive.

I think I can also make this better by supplying a bootloader image (which I have been reluctant to do).  I still want to keep the version check around, because incompatible firmware is the most common source of issues for new PM3 users.

**You have a few options on how to work around this from here:**

1. Reflash with bootloader _and_ firmware built in `git` (this works around https://github.com/Proxmark/proxmark3/issues/12).

2. Reflash with RDV4.0's original bootloader image (I don't know where this is -- sorry) and [the firmware image I provide for AndProx](https://github.com/AndProx/AndProx/releases), and build AndProx from source at `git master`.

3. Recompile AndProx (at `git master` or `v2.0.3`), disabling the version check (`ProxmarkVersion.isSupportedVersion`).

**Comment by misterpyrrhuloxia** [comment]
>1. Reflash with bootloader _and_ firmware built in `git` (this works around [Proxmark/proxmark3#12](https://github.com/Proxmark/proxmark3/issues/12)).

How do I do this on a Mac?

**Comment by misterpyrrhuloxia** [comment]
>1. Reflash with bootloader _and_ firmware built in `git` (this works around [Proxmark/proxmark3#12](https://github.com/Proxmark/proxmark3/issues/12)).

I used this workaround you suggested in my Ubuntu vm and now it's working perfectly. Thanks for your help!  👍

**Comment by micolous** [comment]
No worries!
