### ISSUE TITLE
Official proxmark3 firmware Version 3.1.0 not accepted

### ISSUE THREAD

**Issue by user4757** [AndProx/AndProx#42]
**Describe the bug**

I have flashed official proxmark3 firmware, Version 3.1.0 on my PM3.
(https://github.com/Proxmark/proxmark3/releases)

I installed AndProx 2.0.4 (95).
(https://play.google.com/store/apps/details?id=au.id.micolous.andprox)

When I start AndProx, the PM3 is recognized.

But I get the error message: 
"Proxmark3 firmware update required" 
"Please ... **reflash to official proxmark.org firmware** (v3.1.0/HEAD)"

## Expected behaviour
I expected, that AndProx work with my firmware.

## Proxmark details (required!)
```
proxmark3> hw version
Prox/RFID mark3 RFID instrument          
bootrom: /-suspect 2015-11-04 22:15:34
os: master/v3.1.0-88-g9ebbfd8-suspect 2019-04-30 17:30:01
fpga_lf.bit built for 2s30vq100 on 2015/03/06 at 07:38:04
fpga_hf.bit built for 2s30vq100 on 2019/03/20 at 08:08:07
```

Is it necessary to flash the version from here???
https://github.com/AndProx/AndProx/releases/download/v2.0.4/fullimage.elf.zip

Thanks!

**Comment by micolous** [comment]
The reason this fails is because you have a bootrom/bootloader with an unknown version. For AndProx's version check, it doesn't really matter _which_ version, but as long as it has a proper version string, and not just `/-suspect`.

You should be able to just flash the bootloader from the version of PM3 you built the firmware from, or otherwise you can do it from PM3 v3.1.0.

The os/fullimage you have should be good enough (I'm also running a version from `git master`).

I intend to change this in future.
